export type Account = {
  id: number,
  username: string,
  acct: string,
  display_name: string,
  locked: boolean,
  bot: ?boolean,
  created_at: string,
  note: string,
  url: string,
  avatar: string,
  avatar_static: string,
  header: string,
  header_static: string,
  followers_count: ?number,
  following_count: ?number,
  statuses_count: ?number,
  emojis: mixed[],
  fields: ?(mixed[]),
};

export type Attachment = {
  id: number,
  type: string,
  url: string,
  preview_url: string,
  remote_url: ?string,
  text_url: ?string,
  meta: ?{},
  description: ?string,
};

export type TweetT = {
  id: number,
  created_at: string,
  in_reply_to_id: ?number,
  in_reply_to_account_id: ?number,
  sensitive: boolean,
  spoiler_text: ?string,
  visibility: string,
  language: string,
  uri: string,
  content: string,
  url: string,
  reblogs_count: ?number,
  favourites_count: ?number,
  favourited: boolean,
  reblogged: boolean,
  muted: boolean,
  pinned: boolean,
  reblog: ?boolean,
  application: {
    name: ?string,
    website: ?string,
  },
  account: Account,
  media_attachments: Attachment[],
  mentions: mixed[],
  tags: mixed[],
  emojis: mixed[],
};
